services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: mini-project:local
    ports:
      - '4000:4000'
    env_file:
      - .env.local
    environment:
      NODE_ENV: production
      PORT: 4000
    restart: unless-stopped
